// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TWL.Server.Persistence.Database;

#nullable disable

namespace TWL.Server.Persistence.Database.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260218223352_InitialPlayerSchema")]
    partial class InitialPlayerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TWL.Server.Persistence.Database.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pass_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TWL.Server.Persistence.Database.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("ActivePetInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("active_pet_instance_id");

                    b.Property<int>("Agi")
                        .HasColumnType("integer")
                        .HasColumnName("agi");

                    b.Property<string>("BankJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("bank_json");

                    b.Property<int>("Con")
                        .HasColumnType("integer")
                        .HasColumnName("con");

                    b.Property<long>("DailyGiftAccumulator")
                        .HasColumnType("bigint")
                        .HasColumnName("daily_gift_accumulator");

                    b.Property<int>("Element")
                        .HasColumnType("integer")
                        .HasColumnName("element");

                    b.Property<string>("EquipmentJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("equipment_json");

                    b.Property<int>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int>("ExpToNextLevel")
                        .HasColumnType("integer")
                        .HasColumnName("exp_to_next_level");

                    b.Property<int>("Gold")
                        .HasColumnType("integer")
                        .HasColumnName("gold");

                    b.Property<int>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<string>("InstanceLockoutsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("instance_lockouts_json");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("int");

                    b.Property<string>("InventoryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("inventory_json");

                    b.Property<DateTime>("LastGiftResetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_gift_reset_date");

                    b.Property<DateTime>("LastSaved")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_saved");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PetsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("pets_json");

                    b.Property<long>("PremiumCurrency")
                        .HasColumnType("bigint")
                        .HasColumnName("premium_currency");

                    b.Property<string>("ProcessedOrdersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("processed_orders_json");

                    b.Property<string>("QuestCompletionTimesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("quest_completion_times_json");

                    b.Property<string>("QuestFlagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("quest_flags_json");

                    b.Property<string>("QuestProgressJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("quest_progress_json");

                    b.Property<string>("QuestStartTimesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("quest_start_times_json");

                    b.Property<string>("QuestStatesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("quest_states_json");

                    b.Property<int>("RebirthLevel")
                        .HasColumnType("integer")
                        .HasColumnName("rebirth_level");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("skills_json");

                    b.Property<int>("Sp")
                        .HasColumnType("integer")
                        .HasColumnName("sp");

                    b.Property<int>("StatPoints")
                        .HasColumnType("integer")
                        .HasColumnName("stat_points");

                    b.Property<int>("Str")
                        .HasColumnType("integer")
                        .HasColumnName("str");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("Wis")
                        .HasColumnType("integer")
                        .HasColumnName("wis");

                    b.Property<string>("WorldFlagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("world_flags_json");

                    b.Property<float>("X")
                        .HasColumnType("real")
                        .HasColumnName("x");

                    b.Property<float>("Y")
                        .HasColumnType("real")
                        .HasColumnName("y");

                    b.HasKey("PlayerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("TWL.Server.Persistence.Database.Entities.PlayerEntity", b =>
                {
                    b.HasOne("TWL.Server.Persistence.Database.Entities.AccountEntity", "Account")
                        .WithOne()
                        .HasForeignKey("TWL.Server.Persistence.Database.Entities.PlayerEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
