using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TWL.Server.Persistence.Database.Entities;

namespace TWL.Server.Persistence.Database.Configurations;

public class GuildConfiguration : IEntityTypeConfiguration<GuildEntity>
{
    public void Configure(EntityTypeBuilder<GuildEntity> builder)
    {
        builder.ToTable("guilds");

        builder.HasKey(g => g.GuildId);

        builder.Property(g => g.GuildId)
            .HasColumnName("guild_id")
            .ValueGeneratedNever(); // Use the ID generated by our domain manager for now

        builder.Property(g => g.Name)
            .HasColumnName("name")
            .IsRequired()
            .HasMaxLength(50);

        builder.HasIndex(g => g.Name).IsUnique();

        builder.Property(g => g.LeaderId)
            .HasColumnName("leader_id");

        builder.Property(g => g.MemberIdsJson)
            .HasColumnName("member_ids_json")
            .HasColumnType("jsonb")
            .HasDefaultValue("[]");

        builder.Property(g => g.MemberRanksJson)
            .HasColumnName("member_ranks_json")
            .HasColumnType("jsonb")
            .HasDefaultValue("{}");

        builder.Property(g => g.MemberJoinDatesJson)
            .HasColumnName("member_join_dates_json")
            .HasColumnType("jsonb")
            .HasDefaultValue("{}");

        builder.Property(g => g.StorageItemsJson)
            .HasColumnName("storage_items_json")
            .HasColumnType("jsonb")
            .HasDefaultValue("{}");

        builder.Property(g => g.LastSaved)
            .HasColumnName("last_saved");

        builder.Property(g => g.Version)
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .IsRowVersion();
    }
}
