// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TWL.Server.Persistence.Database;

#nullable disable

namespace TWL.Server.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260217204020_InitialPlayerSchema")]
    partial class InitialPlayerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TWL.Server.Persistence.Database.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Agi")
                        .HasColumnType("integer");

                    b.Property<int>("Con")
                        .HasColumnType("integer");

                    b.Property<long>("DailyGiftAccumulator")
                        .HasColumnType("bigint");

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("ExpToNextLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("Hp")
                        .HasColumnType("integer");

                    b.Property<int>("Int")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastGiftResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSaved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("PremiumCurrency")
                        .HasColumnType("bigint");

                    b.Property<int>("RebirthLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Sp")
                        .HasColumnType("integer");

                    b.Property<int>("StatPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Str")
                        .HasColumnType("integer");

                    b.Property<int>("Wis")
                        .HasColumnType("integer");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TWL.Server.Persistence.Database.PlayerEntity", b =>
                {
                    b.OwnsOne("TWL.Server.Persistence.Database.PlayerSaveDataWrapper", "Data", b1 =>
                        {
                            b1.Property<int>("PlayerEntityId")
                                .HasColumnType("integer");

                            b1.Property<string>("ActivePetInstanceId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.PrimitiveCollection<List<string>>("ProcessedOrders")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<List<string>>("WorldFlags")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("PlayerEntityId");

                            b1.ToTable("Players");

                            b1.ToJson("Data");

                            b1.WithOwner()
                                .HasForeignKey("PlayerEntityId");

                            b1.OwnsMany("TWL.Shared.Domain.Models.Item", "Bank", b2 =>
                                {
                                    b2.Property<int>("PlayerSaveDataWrapperPlayerEntityId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int?>("BoundToId")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "bid");

                                    b2.Property<float>("ForgeSuccessRateBonus")
                                        .HasColumnType("real")
                                        .HasAnnotation("Relational:JsonPropertyName", "f");

                                    b2.Property<int>("ItemId")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "id");

                                    b2.Property<int>("MaxStack")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "m");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "n");

                                    b2.Property<int>("Policy")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "bp");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "q");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "t");

                                    b2.HasKey("PlayerSaveDataWrapperPlayerEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("Players");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerSaveDataWrapperPlayerEntityId");
                                });

                            b1.OwnsMany("TWL.Shared.Domain.Models.Item", "Equipment", b2 =>
                                {
                                    b2.Property<int>("PlayerSaveDataWrapperPlayerEntityId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int?>("BoundToId")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "bid");

                                    b2.Property<float>("ForgeSuccessRateBonus")
                                        .HasColumnType("real")
                                        .HasAnnotation("Relational:JsonPropertyName", "f");

                                    b2.Property<int>("ItemId")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "id");

                                    b2.Property<int>("MaxStack")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "m");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "n");

                                    b2.Property<int>("Policy")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "bp");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "q");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "t");

                                    b2.HasKey("PlayerSaveDataWrapperPlayerEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("Players");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerSaveDataWrapperPlayerEntityId");
                                });

                            b1.OwnsMany("TWL.Shared.Domain.Models.Item", "Inventory", b2 =>
                                {
                                    b2.Property<int>("PlayerSaveDataWrapperPlayerEntityId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int?>("BoundToId")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "bid");

                                    b2.Property<float>("ForgeSuccessRateBonus")
                                        .HasColumnType("real")
                                        .HasAnnotation("Relational:JsonPropertyName", "f");

                                    b2.Property<int>("ItemId")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "id");

                                    b2.Property<int>("MaxStack")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "m");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "n");

                                    b2.Property<int>("Policy")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "bp");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "q");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "t");

                                    b2.HasKey("PlayerSaveDataWrapperPlayerEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("Players");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerSaveDataWrapperPlayerEntityId");
                                });

                            b1.OwnsMany("TWL.Server.Persistence.ServerPetData", "Pets", b2 =>
                                {
                                    b2.Property<int>("PlayerSaveDataWrapperPlayerEntityId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Amity")
                                        .HasColumnType("integer");

                                    b2.Property<bool>("DeathQuestCompleted")
                                        .HasColumnType("boolean");

                                    b2.Property<int>("DefinitionId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Exp")
                                        .HasColumnType("integer");

                                    b2.Property<DateTime?>("ExpirationTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<bool>("HasRebirthed")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("InstanceId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<bool>("IsDead")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("IsLost")
                                        .HasColumnType("boolean");

                                    b2.Property<int>("Level")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.PrimitiveCollection<List<int>>("UnlockedSkillIds")
                                        .IsRequired()
                                        .HasColumnType("integer[]");

                                    b2.HasKey("PlayerSaveDataWrapperPlayerEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("Players");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerSaveDataWrapperPlayerEntityId");
                                });

                            b1.OwnsMany("TWL.Server.Persistence.SkillMasteryData", "Skills", b2 =>
                                {
                                    b2.Property<int>("PlayerSaveDataWrapperPlayerEntityId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Rank")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SkillId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("UsageCount")
                                        .HasColumnType("integer");

                                    b2.HasKey("PlayerSaveDataWrapperPlayerEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("Players");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerSaveDataWrapperPlayerEntityId");
                                });

                            b1.Navigation("Bank");

                            b1.Navigation("Equipment");

                            b1.Navigation("Inventory");

                            b1.Navigation("Pets");

                            b1.Navigation("Skills");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
